
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module partI(

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

    wire outMux0;
    wire outMux1;
	 
	wire[3:0] ram0Output;
    wire[3:0] ram1Output;

    mux2to1 memRAM0
    (
        .memWrite0(SW[9]),
        .memWrite1(0),
        .select(SW[8]),
        .writeOut(outMux0)
    );

    mux2to1 memRAM1
    (
        .memWrite0(0),
        .memWrite1(SW[9]),
        .select(SW[8]),
        .writeOut(outMux1)
    );

    ram16x4 ram0
    (
        .addr(SW[7:4]),
        .mdi(SW[3:0]),
        .mwr(outMux0),
        .clk(KEY[0]),
        .mdo(ram0Output[3:0])
    );

    ram16x4 ram1
    (
        .addr(SW[7:4]),
        .mdi(SW[3:0]),
        .mwr(outMux1),
        .clk(KEY[0]),
        .mdo(ram1Output[3:0])
    );

    hexDisplay ram0DataOutDisplay
    (
        .a(ram0Output[3]),
        .b(ram0Output[2]),
        .c(ram0Output[1]),
        .d(ram0Output[0]),

        .x(HEX0[7:0])
    );

    hexDisplay ram1DataOutDisplay
    (
        .a(ram1Output[3]),
        .b(ram1Output[2]),
        .c(ram1Output[1]),
        .d(ram1Output[0]),

        .x(HEX1[7:0])
    ); 

    hexDisplay dataInDisplay
    (
        .a(SW[3]),
        .b(SW[2]),
        .c(SW[1]),
        .d(SW[0]),

        .x(HEX2[7:0])
    );

    hexDisplay addressDisplay
    (
        .a(SW[7]),
        .b(SW[6]),
        .c(SW[5]),
        .d(SW[4]),

        .x(HEX3[7:0])
    );

    assign HEX4[7:0] = 8'b1111_1111;
    assign HEX5[7:0] = 8'b1111_1111;
endmodule
