mybreak.o: mybreak.c
	gcc -c -g -Wall -Wstrict-prototypes mybreak.c

mybreak: mybreak.o
	gcc -o mybreak mybreak.o 

myheal.o: myheal.c 
	gcc -c -g -Wall -Wstrict-prototypes myheal.c

myheal: myheal.o
	gcc -o myheal myheal.o 

clean:
	rm -rf *.o